// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;

public sealed class ConfigurationEntrySetWorkflowTests
{
    [Fact]
    public async Task ConfigurationEntrySet_InvokesEntityProxyCommand()
    {
        var uniqueRegistry = Substitute.For<IUniqueRegistry>();
        var proxy = Substitute.For<IPlatformConfigurationEntry>();
        var sut = new ConfigurationEntrySetWorkflow(uniqueRegistry);
        var ctx = new WorkflowContext<ConfigurationEntrySetCommand>(new ConfigurationEntrySetCommand("sample-1", "sample-2", "sample-3", "sample-4", "sample-5", "sample-6"), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.ConfigurationEntrySet(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).ConfigurationEntrySet(Arg.Any<ConfigurationEntrySetRequest>(), Arg.Any<CancellationToken>());
    }
}