// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;

public sealed class ProductCreateWorkflowTests
{
    [Fact]
    public async Task ProductCreate_InvokesEntityProxyCommand()
    {
        var proxy = Substitute.For<IPlatformProduct>();
        var sut = new ProductCreateWorkflow();
        var ctx = new WorkflowContext<ProductCreateCommand>(new ProductCreateCommand("sample-1", "sample-2"), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.ProductCreate(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).ProductCreate(Arg.Any<ProductCreateRequest>(), Arg.Any<CancellationToken>());
    }
}