// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;

public sealed class RoleEnableWorkflowTests
{
    [Fact]
    public async Task RoleEnable_InvokesEntityProxyCommand()
    {
        var proxy = Substitute.For<IPlatformRole>();
        var sut = new RoleEnableWorkflow();
        var ctx = new WorkflowContext<RoleEnableCommand>(new RoleEnableCommand(new Guid(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.RoleEnable(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).RoleEnable(Arg.Any<CancellationToken>());
    }
}