// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;

public sealed class RoleDisableWorkflowTests
{
    [Fact]
    public async Task RoleDisable_InvokesEntityProxyCommand()
    {
        var proxy = Substitute.For<IPlatformRole>();
        var sut = new RoleDisableWorkflow();
        var ctx = new WorkflowContext<RoleDisableCommand>(new RoleDisableCommand(new Guid(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.RoleDisable(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).RoleDisable(Arg.Any<CancellationToken>());
    }
}