// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;
public sealed class RoleCreateWorkflowTests
{
    [Fact]
    public async Task RoleCreate_InvokesEntityProxyCommand()
    {
        var uniqueRegistry = Substitute.For<IUniqueRegistry>();
        var proxy = Substitute.For<IPlatformRole>();
        var sut = new RoleCreateWorkflow(uniqueRegistry);
        var ctx = new WorkflowContext<RoleCreateCommand>(new RoleCreateCommand("sample-1", "sample-2"), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.RoleCreate(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).RoleCreate(Arg.Any<RoleCreateRequest>(), Arg.Any<CancellationToken>());
    }
}