// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Tests;
public sealed class TenantApiKeyIssueWorkflowTests
{
    [Fact]
    public async Task IssueApiKey_InvokesEntityProxyCommand()
    {
        var proxy = Substitute.For<IPlatformTenant>();
        var sut = new TenantApiKeyIssueWorkflow();
        var ctx = new WorkflowContext<TenantApiKeyIssueCommand>(new TenantApiKeyIssueCommand(new Guid(1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0), "sample-2", "sample-3", "sample-4", new DateTimeOffset(2024, 1, 1, 0, 0, 0, TimeSpan.Zero).AddSeconds(5)), TenantIdentifier.Empty, UserIdentifier.Empty, CorrelationIdentifier.Empty, ProductIdentifier.Empty, CommandIdentifier.Empty);
        try
        {
            await sut.IssueApiKey(proxy, ctx, CancellationToken.None);
        }
        catch
        {
        }

        await proxy.Received(1).IssueApiKey(Arg.Any<IssueApiKeyRequest>(), Arg.Any<CancellationToken>());
    }
}