// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Resolvers.Tests;
public sealed class ProductCreateResolverStep2Tests
{
    [Fact]
    public async Task Resolve_WhenKeyNotYetReserved_ReservesItAndGeneratesNewEntityIdentifier()
    {
        var entityTypeResolver = Substitute.For<IEntityTypeResolver>();
        var uniqueIdentifierProvider = Substitute.For<IUniqueIdentifierProvider>();
        var uniqueRegistry = Substitute.For<IUniqueRegistry>();
        var expectedId = Guid.NewGuid();
        uniqueIdentifierProvider.GetNext().Returns(expectedId);
        uniqueRegistry.Ensure(Arg.Any<UniqueRegistryKey>(), Arg.Any<CancellationToken>()).Returns(true);
        var sut = new ProductCreateResolverStep2(entityTypeResolver, uniqueIdentifierProvider, uniqueRegistry);
        var result = await sut.Resolve(new ProductCreateCommand("sample-1", "sample-2"), WorkflowContext.Empty, CancellationToken.None);
        Assert.Equal(expectedId, result.Value);
        uniqueIdentifierProvider.Received(1).GetNext();
    }

    [Fact]
    public async Task Resolve_WhenKeyAlreadyReserved_ReturnsEmpty()
    {
        var entityTypeResolver = Substitute.For<IEntityTypeResolver>();
        var uniqueIdentifierProvider = Substitute.For<IUniqueIdentifierProvider>();
        var uniqueRegistry = Substitute.For<IUniqueRegistry>();
        uniqueRegistry.Ensure(Arg.Any<UniqueRegistryKey>(), Arg.Any<CancellationToken>()).Returns(false);
        var sut = new ProductCreateResolverStep2(entityTypeResolver, uniqueIdentifierProvider, uniqueRegistry);
        var result = await sut.Resolve(new ProductCreateCommand("sample-1", "sample-2"), WorkflowContext.Empty, CancellationToken.None);
        Assert.Equal(EntityIdentifier.Empty, result);
        uniqueIdentifierProvider.DidNotReceive().GetNext();
    }
}