// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using NSubstitute;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Resolvers.Tests;
public sealed class TenantCreateResolverStep1Tests
{
    [Fact]
    public async Task Resolve_LooksUpEntityIdentifierInUniqueRegistry()
    {
        var uniqueRegistry = Substitute.For<IUniqueRegistry>();
        var expected = new EntityIdentifier(new EntityType("test-entity"), Guid.NewGuid());
        uniqueRegistry.Get(Arg.Any<UniqueRegistryKey>(), Arg.Any<CancellationToken>()).Returns(expected);
        var sut = new TenantCreateResolverStep1(uniqueRegistry);
        var result = await sut.Resolve(new TenantCreateCommand("sample-1", "sample-2"), WorkflowContext.Empty, CancellationToken.None);
        Assert.Equal(expected, result);
        await uniqueRegistry.Received(1).Get(Arg.Any<UniqueRegistryKey>(), Arg.Any<CancellationToken>());
    }
}