// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;
/// <summary>Creates a configuration entry for the given key.</summary>
[Command("configuration-entry-set")]
public sealed record ConfigurationEntrySetCommand(string Key, string SchemaKey, string PropertyKey, string ScopeKind, string? ScopeId, string Value);
/// <summary>Workflow implementing the 'configuration-entry-set' process.</summary>
[OrchestratorWorkflow("platform.configuration-entry-set", Name = "ConfigurationEntrySet Workflow", Roles = new[] { "Administrator" })]
public partial class ConfigurationEntrySetWorkflow
{
    /// <summary>Creates a configuration entry for the given key.</summary>
    [OnStart]
    public async Task ConfigurationEntrySet(IPlatformConfigurationEntry proxy, WorkflowContext<ConfigurationEntrySetCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new ConfigurationEntrySetRequest(new ConfigurationEntryKey(ctx.Request.Key), new ConfigurationSchemaKey(ctx.Request.SchemaKey), new ConfigurationPropertyKey(ctx.Request.PropertyKey), new ConfigurationScopeKind(ctx.Request.ScopeKind), ctx.Request.ScopeId, new ConfigurationValue(ctx.Request.Value));
        await proxy.ConfigurationEntrySet(request, cancellationToken).ConfigureAwait(false);
    }
}