// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;
/// <summary>Creates a new product account.</summary>
[Command("platform-product-create")]
public sealed record ProductCreateCommand(string Name, string Key);
/// <summary>Workflow implementing the 'product-create' process.</summary>
[OrchestratorWorkflow("platform.product-create", Name = "ProductCreate Workflow", Roles = new[] { "Administrator" })]
public partial class ProductCreateWorkflow
{
    /// <summary>Creates a new product account.</summary>
    [OnStart]
    public async Task ProductCreate(IPlatformProduct proxy, WorkflowContext<ProductCreateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new ProductCreateRequest(new Domaincontext.Platform.ProductName(ctx.Request.Name), new Domaincontext.Platform.ProductKey(ctx.Request.Key));
        await proxy.ProductCreate(request, cancellationToken).ConfigureAwait(false);
    }
}