// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Renames the specified product.</summary>
[Command("platform-product-update")]
public sealed record ProductUpdateCommand(Guid ProductId, string Name);
/// <summary>Workflow implementing the 'product-update' process.</summary>
[OrchestratorWorkflow("platform.product-update", Name = "ProductUpdate Workflow", Roles = new[] { "Administrator", "System" })]
public partial class ProductUpdateWorkflow
{
    /// <summary>Renames the specified product.</summary>
    [OnStart]
    public async Task ProductUpdate(IPlatformProduct proxy, WorkflowContext<ProductUpdateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new ProductUpdateRequest(new Domaincontext.Platform.ProductName(ctx.Request.Name));
        await proxy.ProductUpdate(request, cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'product-update' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface IProductUpdateInvoker : IWorkflowInvoker<ProductUpdateCommand>
{
}

/// <summary>In-process IProductUpdateInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class ProductUpdateLocalInvoker : IProductUpdateInvoker
{
    private readonly IOrchestrator _orchestrator;
    public ProductUpdateLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<ProductUpdateCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<ProductUpdateWorkflow, ProductUpdateCommand>(context, cancellationToken);
}