// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Enables the specified product.</summary>
[Command("product-enable")]
public sealed record ProductEnableCommand(Guid ProductId);
/// <summary>Workflow implementing the 'product-enable' process.</summary>
[OrchestratorWorkflow("platform.product-enable", Name = "ProductEnable Workflow", Roles = new[] { "Administrator" })]
public partial class ProductEnableWorkflow
{
    /// <summary>Enables the specified product.</summary>
    [OnStart]
    public async Task ProductEnable(IPlatformProduct proxy, WorkflowContext<ProductEnableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.ProductEnable(cancellationToken).ConfigureAwait(false);
    }
}