// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Disables the specified product.</summary>
[Command("platform-product-disable")]
public sealed record ProductDisableCommand(Guid ProductId, string? Reason);
/// <summary>Workflow implementing the 'product-disable' process.</summary>
[OrchestratorWorkflow("platform.product-disable", Name = "ProductDisable Workflow", Roles = new[] { "Administrator", "System" })]
public partial class ProductDisableWorkflow
{
    /// <summary>Disables the specified product.</summary>
    [OnStart]
    public async Task ProductDisable(IPlatformProduct proxy, WorkflowContext<ProductDisableCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new ProductDisableRequest(ctx.Request.Reason is null ? null : new ProductDisableReason(ctx.Request.Reason));
        await proxy.ProductDisable(request, cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'product-disable' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface IProductDisableInvoker : IWorkflowInvoker<ProductDisableCommand>
{
}

/// <summary>In-process IProductDisableInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class ProductDisableLocalInvoker : IProductDisableInvoker
{
    private readonly IOrchestrator _orchestrator;
    public ProductDisableLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<ProductDisableCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<ProductDisableWorkflow, ProductDisableCommand>(context, cancellationToken);
}