// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Deletes the specified product.</summary>
[Command("platform-product-delete")]
public sealed record ProductDeleteCommand(Guid ProductId);
/// <summary>Workflow implementing the 'product-delete' process.</summary>
[OrchestratorWorkflow("platform.product-delete", Name = "ProductDelete Workflow", Roles = new[] { "Administrator", "System" })]
public partial class ProductDeleteWorkflow
{
    /// <summary>Deletes the specified product.</summary>
    [OnStart]
    public async Task ProductDelete(IPlatformProduct proxy, WorkflowContext<ProductDeleteCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.ProductDelete(cancellationToken).ConfigureAwait(false);
    }
}