// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Creates a new role.</summary>
[Command("role-create")]
public sealed record RoleCreateCommand(string Name, string Key);
/// <summary>Workflow implementing the 'role-create' process.</summary>
[OrchestratorWorkflow("platform.role-create", Name = "RoleCreate Workflow", Roles = new[] { "Administrator", "System" })]
public partial class RoleCreateWorkflow
{
    private readonly IUniqueRegistry _uniqueRegistry;
    /// <summary>Initializes a new instance of the RoleCreateWorkflow class.</summary>
    public RoleCreateWorkflow(IUniqueRegistry uniqueRegistry)
    {
        _uniqueRegistry = uniqueRegistry ?? throw new ArgumentNullException(nameof(uniqueRegistry));
    }

    /// <summary>Creates a new role.</summary>
    [OnStart]
    public async Task RoleCreate(IPlatformRole proxy, WorkflowContext<RoleCreateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new RoleCreateRequest(new RoleName(ctx.Request.Name), new RoleKey(ctx.Request.Key));
        await proxy.RoleCreate(request, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>Confirms the reserved role key in the unique registry once the role is created.</summary>
    [WhenEvent]
    public async Task OnRoleCreated(Domaincontext.Platform.RoleCreated payload, EventContext eventContext, WorkflowContext context, CancellationToken cancellationToken)
    {
        await _uniqueRegistry.Confirm(eventContext.EntityId, new UniqueRegistryKey(Constants.RoleKeyUniqueKey, payload.Key.Value), cancellationToken).ConfigureAwait(false);
    }
}