// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Enables the specified role.</summary>
[Command("role-enable")]
public sealed record RoleEnableCommand(Guid RoleId);
/// <summary>Workflow implementing the 'role-enable' process.</summary>
[OrchestratorWorkflow("platform.role-enable", Name = "RoleEnable Workflow", Roles = new[] { "Administrator" })]
public partial class RoleEnableWorkflow
{
    /// <summary>Enables the specified role.</summary>
    [OnStart]
    public async Task RoleEnable(IPlatformRole proxy, WorkflowContext<RoleEnableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.RoleEnable(cancellationToken).ConfigureAwait(false);
    }
}