// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;
/// <summary>Disables the specified role.</summary>
[Command("role-disable")]
public sealed record RoleDisableCommand(Guid RoleId);
/// <summary>Workflow implementing the 'role-disable' process.</summary>
[OrchestratorWorkflow("platform.role-disable", Name = "RoleDisable Workflow", Roles = new[] { "Administrator" })]
public partial class RoleDisableWorkflow
{
    /// <summary>Disables the specified role.</summary>
    [OnStart]
    public async Task RoleDisable(IPlatformRole proxy, WorkflowContext<RoleDisableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.RoleDisable(cancellationToken).ConfigureAwait(false);
    }
}