// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Enables the specified role.</summary>
[Command("platform-role-enable")]
public sealed record RoleEnableCommand(Guid RoleId);
/// <summary>Workflow implementing the 'role-enable' process.</summary>
[OrchestratorWorkflow("platform.role-enable", Name = "RoleEnable Workflow", Roles = new[] { "Administrator", "System" })]
public partial class RoleEnableWorkflow
{
    /// <summary>Enables the specified role.</summary>
    [OnStart]
    public async Task RoleEnable(IPlatformRole proxy, WorkflowContext<RoleEnableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.RoleEnable(cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'role-enable' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface IRoleEnableInvoker : IWorkflowInvoker<RoleEnableCommand>
{
}

/// <summary>In-process IRoleEnableInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class RoleEnableLocalInvoker : IRoleEnableInvoker
{
    private readonly IOrchestrator _orchestrator;
    public RoleEnableLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<RoleEnableCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<RoleEnableWorkflow, RoleEnableCommand>(context, cancellationToken);
}