// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Renames the specified role.</summary>
[Command("platform-role-update")]
public sealed record RoleUpdateCommand(Guid RoleId, string Name);
/// <summary>Workflow implementing the 'role-update' process.</summary>
[OrchestratorWorkflow("platform.role-update", Name = "RoleUpdate Workflow", Roles = new[] { "Administrator", "System" })]
public partial class RoleUpdateWorkflow
{
    /// <summary>Renames the specified role.</summary>
    [OnStart]
    public async Task RoleUpdate(IPlatformRole proxy, WorkflowContext<RoleUpdateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new RoleUpdateRequest(new RoleName(ctx.Request.Name));
        await proxy.RoleUpdate(request, cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'role-update' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface IRoleUpdateInvoker : IWorkflowInvoker<RoleUpdateCommand>
{
}

/// <summary>In-process IRoleUpdateInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class RoleUpdateLocalInvoker : IRoleUpdateInvoker
{
    private readonly IOrchestrator _orchestrator;
    public RoleUpdateLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<RoleUpdateCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<RoleUpdateWorkflow, RoleUpdateCommand>(context, cancellationToken);
}