// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;
/// <summary>Disables the specified tenant.</summary>
[Command("tenant-disable")]
public sealed record TenantDisableCommand(Guid TenantId, string? Reason);
/// <summary>Workflow implementing the 'tenant-disable' process.</summary>
[OrchestratorWorkflow("platform.tenant-disable", Name = "TenantDisable Workflow", Roles = new[] { "Administrator" })]
public partial class TenantDisableWorkflow
{
    /// <summary>Disables the specified tenant.</summary>
    [OnStart]
    public async Task Disable(IPlatformTenant proxy, WorkflowContext<TenantDisableCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new DisableRequest(ctx.Request.Reason is null ? null : new TenantDisableReason(ctx.Request.Reason));
        await proxy.Disable(request, cancellationToken).ConfigureAwait(false);
    }
}