// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Issues an API key for the specified tenant.</summary>
[Command("tenant-api-key-issue")]
public sealed record TenantApiKeyIssueCommand(Guid TenantId, string Name, string? Description, string RawApiKey, DateTimeOffset ExpiresAt);
/// <summary>Workflow implementing the 'tenant-api-key-issue' process.</summary>
[OrchestratorWorkflow("platform.tenant-api-key-issue", Name = "TenantApiKeyIssue Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantApiKeyIssueWorkflow
{
    /// <summary>Issues an API key for the specified tenant.</summary>
    [OnStart]
    public async Task IssueApiKey(IPlatformTenant proxy, WorkflowContext<TenantApiKeyIssueCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new IssueApiKeyRequest(new ApiKeyName(ctx.Request.Name), ctx.Request.Description is null ? null : new ApiKeyDescription(ctx.Request.Description), await ProvideKeyHash(ctx, cancellationToken).ConfigureAwait(false), new ApiKeyExpiresAt(ctx.Request.ExpiresAt), new Appfoundation.Core.UserIdentifier(ctx.UserIdentifier.Value));
        await proxy.IssueApiKey(request, cancellationToken).ConfigureAwait(false);
    }

    private partial Task<ApiKeyHash> ProvideKeyHash(WorkflowContext<TenantApiKeyIssueCommand> ctx, CancellationToken cancellationToken);
}