// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Creates a new tenant account.</summary>
[Command("platform-create")]
public sealed record TenantCreateCommand(string Name, string Key);
/// <summary>Workflow implementing the 'tenant-create' process.</summary>
[OrchestratorWorkflow("platform.tenant-create", Name = "TenantCreate Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantCreateWorkflow
{
    /// <summary>Creates a new tenant account.</summary>
    [OnStart]
    public async Task Create(IPlatformTenant proxy, WorkflowContext<TenantCreateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new CreateRequest(new Domaincontext.Platform.TenantName(ctx.Request.Name), new Domaincontext.Platform.TenantKey(ctx.Request.Key));
        await proxy.Create(request, cancellationToken).ConfigureAwait(false);
    }
}