// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Renames the specified tenant.</summary>
[Command("platform-tenant-update")]
public sealed record TenantUpdateCommand(Guid TenantId, string Name);
/// <summary>Workflow implementing the 'tenant-update' process.</summary>
[OrchestratorWorkflow("platform.tenant-update", Name = "TenantUpdate Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantUpdateWorkflow
{
    /// <summary>Renames the specified tenant.</summary>
    [OnStart]
    public async Task TenantUpdate(IPlatformTenant proxy, WorkflowContext<TenantUpdateCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new TenantUpdateRequest(new Domaincontext.Platform.TenantName(ctx.Request.Name));
        await proxy.TenantUpdate(request, cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'tenant-update' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface ITenantUpdateInvoker : IWorkflowInvoker<TenantUpdateCommand>
{
}

/// <summary>In-process ITenantUpdateInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class TenantUpdateLocalInvoker : ITenantUpdateInvoker
{
    private readonly IOrchestrator _orchestrator;
    public TenantUpdateLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<TenantUpdateCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<TenantUpdateWorkflow, TenantUpdateCommand>(context, cancellationToken);
}