// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Enables the specified tenant.</summary>
[Command("platform-enable")]
public sealed record TenantEnableCommand(Guid TenantId);
/// <summary>Workflow implementing the 'tenant-enable' process.</summary>
[OrchestratorWorkflow("platform.tenant-enable", Name = "TenantEnable Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantEnableWorkflow
{
    /// <summary>Enables the specified tenant.</summary>
    [OnStart]
    public async Task Enable(IPlatformTenant proxy, WorkflowContext<TenantEnableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.Enable(cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'tenant-enable' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface ITenantEnableInvoker : IWorkflowInvoker<TenantEnableCommand>
{
}

/// <summary>In-process ITenantEnableInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class TenantEnableLocalInvoker : ITenantEnableInvoker
{
    private readonly IOrchestrator _orchestrator;
    public TenantEnableLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<TenantEnableCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<TenantEnableWorkflow, TenantEnableCommand>(context, cancellationToken);
}