// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Enables the specified tenant.</summary>
[Command("tenant-enable")]
public sealed record TenantEnableCommand(Guid TenantId);
/// <summary>Workflow implementing the 'tenant-enable' process.</summary>
[OrchestratorWorkflow("platform.tenant-enable", Name = "TenantEnable Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantEnableWorkflow
{
    /// <summary>Enables the specified tenant.</summary>
    [OnStart]
    public async Task Enable(IPlatformTenant proxy, WorkflowContext<TenantEnableCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.Enable(cancellationToken).ConfigureAwait(false);
    }
}