// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Revokes the specified API key for the given tenant.</summary>
[Command("tenant-api-key-revoke")]
public sealed record TenantApiKeyRevokeCommand(Guid TenantId, string KeyHash);
/// <summary>Workflow implementing the 'tenant-api-key-revoke' process.</summary>
[OrchestratorWorkflow("platform.tenant-api-key-revoke", Name = "TenantApiKeyRevoke Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantApiKeyRevokeWorkflow
{
    /// <summary>Revokes the specified API key for the given tenant.</summary>
    [OnStart]
    public async Task RevokeApiKey(IPlatformTenant proxy, WorkflowContext<TenantApiKeyRevokeCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new RevokeApiKeyRequest(new ApiKeyHash(ctx.Request.KeyHash));
        await proxy.RevokeApiKey(request, cancellationToken).ConfigureAwait(false);
    }
}