// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Disables the specified tenant.</summary>
[Command("platform-disable")]
public sealed record TenantDisableCommand(Guid TenantId, string? Reason);
/// <summary>Workflow implementing the 'tenant-disable' process.</summary>
[OrchestratorWorkflow("platform.tenant-disable", Name = "TenantDisable Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantDisableWorkflow
{
    /// <summary>Disables the specified tenant.</summary>
    [OnStart]
    public async Task Disable(IPlatformTenant proxy, WorkflowContext<TenantDisableCommand> ctx, CancellationToken cancellationToken)
    {
        var request = new DisableRequest(ctx.Request.Reason is null ? null : new TenantDisableReason(ctx.Request.Reason));
        await proxy.Disable(request, cancellationToken).ConfigureAwait(false);
    }
}

/// <summary>Uniform entry point for starting the 'tenant-disable' workflow, regardless of whether the caller and the workflow share an assembly.</summary>
public interface ITenantDisableInvoker : IWorkflowInvoker<TenantDisableCommand>
{
}

/// <summary>In-process ITenantDisableInvoker implementation, registered whenever this workflow group is hosted directly in the current assembly.</summary>
internal sealed class TenantDisableLocalInvoker : ITenantDisableInvoker
{
    private readonly IOrchestrator _orchestrator;
    public TenantDisableLocalInvoker(IOrchestrator orchestrator)
    {
        _orchestrator = orchestrator ?? throw new ArgumentNullException(nameof(orchestrator));
    }

    public Task InvokeAsync(WorkflowContext<TenantDisableCommand> context, CancellationToken cancellationToken) => _orchestrator.StartWorkflowAsync<TenantDisableWorkflow, TenantDisableCommand>(context, cancellationToken);
}