// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Contract.Integration;
using Appfoundation.Contract.Security;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Attributes;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform;

namespace Workflowgroup.Platform.Workflow;

/// <summary>Deletes the specified tenant.</summary>
[Command("platform-tenant-delete")]
public sealed record TenantDeleteCommand(Guid TenantId);
/// <summary>Workflow implementing the 'tenant-delete' process.</summary>
[OrchestratorWorkflow("platform.tenant-delete", Name = "TenantDelete Workflow", Roles = new[] { "Administrator", "System" })]
public partial class TenantDeleteWorkflow
{
    /// <summary>Deletes the specified tenant.</summary>
    [OnStart]
    public async Task TenantDelete(IPlatformTenant proxy, WorkflowContext<TenantDeleteCommand> ctx, CancellationToken cancellationToken)
    {
        await proxy.TenantDelete(cancellationToken).ConfigureAwait(false);
    }
}