// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Resolvers;
using Domaincontext.Platform;

internal sealed class ConfigurationEntrySetResolverStep2 : IEntityIdentifierResolver<ConfigurationEntrySetCommand>
{
    private readonly IEntityTypeResolver _entityTypeResolver;
    private readonly IUniqueIdentifierProvider _uniqueIdentifierProvider;
    private readonly IUniqueRegistry _uniqueRegistry;
    public ConfigurationEntrySetResolverStep2(IEntityTypeResolver entityTypeResolver, IUniqueIdentifierProvider uniqueIdentifierProvider, IUniqueRegistry uniqueRegistry)
    {
        _entityTypeResolver = entityTypeResolver ?? throw new ArgumentNullException(nameof(entityTypeResolver));
        _uniqueIdentifierProvider = uniqueIdentifierProvider ?? throw new ArgumentNullException(nameof(uniqueIdentifierProvider));
        _uniqueRegistry = uniqueRegistry ?? throw new ArgumentNullException(nameof(uniqueRegistry));
    }

    public async Task<EntityIdentifier> Resolve(ConfigurationEntrySetCommand input, WorkflowContext context, CancellationToken cancellationToken)
    {
        var reserved = await _uniqueRegistry.Ensure(new UniqueRegistryKey(Workflowgroup.Platform.Constants.ConfigurationEntryKeyUniqueKey, input.Key), cancellationToken).ConfigureAwait(false);
        if (!reserved)
            return EntityIdentifier.Empty;
        var newId = _uniqueIdentifierProvider.GetNext();
        var entityType = _entityTypeResolver.Resolve<IConfigurationEntry>();
        return new EntityIdentifier(entityType, newId);
    }
}