// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Resolvers;
internal sealed class ConfigurationEntrySetResolverStep1 : IEntityIdentifierResolver<ConfigurationEntrySetCommand>
{
    private readonly IUniqueRegistry _uniqueRegistry;
    public ConfigurationEntrySetResolverStep1(IUniqueRegistry uniqueRegistry)
    {
        _uniqueRegistry = uniqueRegistry ?? throw new ArgumentNullException(nameof(uniqueRegistry));
    }

    public async Task<EntityIdentifier> Resolve(ConfigurationEntrySetCommand input, WorkflowContext context, CancellationToken cancellationToken)
    {
        return await _uniqueRegistry.Get(new UniqueRegistryKey(Workflowgroup.Platform.Constants.ConfigurationEntryKeyUniqueKey, input.Key), cancellationToken).ConfigureAwait(false) ?? EntityIdentifier.Empty;
    }
}