// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Contract.Domain;
using Appfoundation.Core;
using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Workflowgroup.Platform.Workflow;

namespace Workflowgroup.Platform.Workflow.Resolvers;

using Domaincontext.Platform;

internal sealed class RoleEnableResolver : IEntityIdentifierResolver<RoleEnableCommand>
{
    private readonly IEntityTypeResolver _entityTypeResolver;
    public RoleEnableResolver(IEntityTypeResolver entityTypeResolver)
    {
        _entityTypeResolver = entityTypeResolver ?? throw new ArgumentNullException(nameof(entityTypeResolver));
    }

    public Task<EntityIdentifier> Resolve(RoleEnableCommand input, WorkflowContext context, CancellationToken cancellationToken)
    {
        var entityType = _entityTypeResolver.Resolve<IRole>();
        return Task.FromResult(new EntityIdentifier(entityType, input.RoleId));
    }
}