// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

namespace Workflowgroup.Platform;

/// <summary>Unique-registry key constants for the 'platform' workflow group.</summary>
public static class Constants
{
    /// <summary>Unique-registry key for 'configuration-entry-key'.</summary>
    public const string ConfigurationEntryKeyUniqueKey = "configuration-entry-key";
    /// <summary>Unique-registry key for 'product-key'.</summary>
    public const string ProductKeyUniqueKey = "product-key";
    /// <summary>Unique-registry key for 'role-key'.</summary>
    public const string RoleKeyUniqueKey = "role-key";
    /// <summary>Unique-registry key for 'tenant-key'.</summary>
    public const string TenantKeyUniqueKey = "tenant-key";
}