// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

using Appfoundation.Orchestrator.Abstraction;
using Appfoundation.Orchestrator.Abstraction.Core;
using Domaincontext.Platform.ConfigurationEntry;
using Domaincontext.Platform.Product;
using Domaincontext.Platform.Role;
using Domaincontext.Platform.Tenant;
using Microsoft.Extensions.DependencyInjection;
using Workflowgroup.Platform.Workflow;
using Workflowgroup.Platform.Workflow.Resolvers;

namespace Workflowgroup.Platform;

/// <summary>Mechanical DI registrations for the platform workflow group — regenerated whenever the group's workflows change.</summary>
public static partial class ModuleBootstrapper
{
    private static IServiceCollection AddPlatformWorkflowsGenerated(this IServiceCollection serviceCollection)
    {
        serviceCollection.AddWorkflowCommandMappings().For<ConfigurationEntrySetWorkflow, ConfigurationEntrySetCommand>().For<ProductCreateWorkflow, ProductCreateCommand>().For<ProductDeleteWorkflow, ProductDeleteCommand>().For<ProductDisableWorkflow, ProductDisableCommand>().For<ProductEnableWorkflow, ProductEnableCommand>().For<RoleCreateWorkflow, RoleCreateCommand>().For<RoleDisableWorkflow, RoleDisableCommand>().For<RoleEnableWorkflow, RoleEnableCommand>().For<TenantApiKeyIssueWorkflow, TenantApiKeyIssueCommand>().For<TenantApiKeyRevokeWorkflow, TenantApiKeyRevokeCommand>().For<TenantCreateWorkflow, TenantCreateCommand>().For<TenantDeleteWorkflow, TenantDeleteCommand>().For<TenantDisableWorkflow, TenantDisableCommand>().For<TenantEnableWorkflow, TenantEnableCommand>();
        serviceCollection.AddGeneratedWorkflows();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ConfigurationEntrySetCommand>, ConfigurationEntrySetResolverStep1>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ConfigurationEntrySetCommand>, ConfigurationEntrySetResolverStep2>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ProductCreateCommand>, ProductCreateResolverStep1>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ProductCreateCommand>, ProductCreateResolverStep2>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ProductDeleteCommand>, ProductDeleteResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ProductDisableCommand>, ProductDisableResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<ProductEnableCommand>, ProductEnableResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<RoleCreateCommand>, RoleCreateResolverStep1>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<RoleCreateCommand>, RoleCreateResolverStep2>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<RoleDisableCommand>, RoleDisableResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<RoleEnableCommand>, RoleEnableResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantApiKeyIssueCommand>, TenantApiKeyIssueResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantApiKeyRevokeCommand>, TenantApiKeyRevokeResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantCreateCommand>, TenantCreateResolverStep1>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantCreateCommand>, TenantCreateResolverStep2>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantDeleteCommand>, TenantDeleteResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantDisableCommand>, TenantDisableResolver>();
        serviceCollection.AddScoped<IEntityIdentifierResolver<TenantEnableCommand>, TenantEnableResolver>();
        serviceCollection.AddConfigurationEntryEntity();
        serviceCollection.AddProductEntity();
        serviceCollection.AddRoleEntity();
        serviceCollection.AddTenantEntity();
        return serviceCollection;
    }
}