// <auto-generated>
//   Generated by the App Builder platform code generator from platform-definition JSON.
//   Regenerating will overwrite this file. Do not edit by hand.
// </auto-generated>

#nullable enable

namespace Workflowgroup.Platform;
/// <summary>The platform's seed role dictionary — administrator/user by default, extensible via platform/roles/*.json.</summary>
public static class RoleDictionary
{
    /// <summary>Every role dictionary entry (platform/roles/*.json), in file order.</summary>
    public static readonly (string Key, string Name)[] Entries = [("administrator", "Administrator"), ("user", "User")];
}